config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: %i[index show]

  resources :games, only: %i[create show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: %i[new create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>Millionaire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <%= link_to 'Millionaire', root_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <div class="navbar-form navbar-right">

          <% if current_user.is_admin? %>
            <%# Ссылка на админку %>
            <%= link_to 'Админка', rails_admin_path, class: 'btn navbar-btn btn-danger btn-xs' %>
            <%= link_to 'Залить новые вопросы', new_questions_path, class: 'btn navbar-btn btn-warning btn-xs' %>
          <% end %>


          <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                      user_path(current_user),
                      class: 'btn navbar-btn'
          %>
          <%= link_to 'Новая игра', games_path, method: :post, class: 'btn navbar-btn btn-success btn-xs' %>
          <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-info btn-xs navbar-btn' %>
        </div>
      <% else %>
        <div class="navbar-form navbar-right">
          <%= link_to 'Войти', new_user_session_path, class: 'btn btn-primary' %>
          <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>

    <footer class="footer mt-auto py-3">
      <div class="container-fluid">
      <span class="text-muted"> &copy; <%= link_to 'Хороший программист', 'https://goodprogrammer.ru/' %>
        2014 &mdash; &infin; </span>
      </div>
    </footer>
  </div>

  </body>
</html>